name: Secrets Guard

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install sops & age
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sops age
          sops --version || true
          age --version || true
      - name: Run secrets-guard
        run: |
          bash infra/server/bin/secrets-guard
